services:
  simple-budget:
    container_name: simple-budget
    image: simple-budget
    build:
      dockerfile: prod.Dockerfile
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    user: 1000:1000
    env_file: .env
    ports:
      - "3035:3000"
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DB_FILE_PATH}:/app/database.db
