services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: bridge
